//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoModPlugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AutoLegality : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutoLegality defaultInstance = ((AutoLegality)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutoLegality())));
        
        public static AutoLegality Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flagbrew.org")]
        public string GPSSBaseURL {
            get {
                return ((string)(this["GPSSBaseURL"]));
            }
            set {
                this["GPSSBaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetMatchingBalls {
            get {
                return ((bool)(this["SetMatchingBalls"]));
            }
            set {
                this["SetMatchingBalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetAllLegalRibbons {
            get {
                return ((bool)(this["SetAllLegalRibbons"]));
            }
            set {
                this["SetAllLegalRibbons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTrainerData {
            get {
                return ((bool)(this["UseTrainerData"]));
            }
            set {
                this["UseTrainerData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCompetitiveMarkings {
            get {
                return ((bool)(this["UseCompetitiveMarkings"]));
            }
            set {
                this["UseCompetitiveMarkings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMarkings {
            get {
                return ((bool)(this["UseMarkings"]));
            }
            set {
                this["UseMarkings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseXOROSHIRO {
            get {
                return ((bool)(this["UseXOROSHIRO"]));
            }
            set {
                this["UseXOROSHIRO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.65")]
        public string LatestIP {
            get {
                return ((string)(this["LatestIP"]));
            }
            set {
                this["LatestIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetRandomTracker {
            get {
                return ((bool)(this["SetRandomTracker"]));
            }
            set {
                this["SetRandomTracker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrioritizeEvent {
            get {
                return ((bool)(this["PrioritizeEvent"]));
            }
            set {
                this["PrioritizeEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceSpecifiedBall {
            get {
                return ((bool)(this["ForceSpecifiedBall"]));
            }
            set {
                this["ForceSpecifiedBall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableEasterEggs {
            get {
                return ((bool)(this["EnableEasterEggs"]));
            }
            set {
                this["EnableEasterEggs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrioritizeGame {
            get {
                return ((bool)(this["PrioritizeGame"]));
            }
            set {
                this["PrioritizeGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USBBotBasePreferred {
            get {
                return ((bool)(this["USBBotBasePreferred"]));
            }
            set {
                this["USBBotBasePreferred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public global::PKHeX.Core.GameVersion PriorityGameVersion {
            get {
                return ((global::PKHeX.Core.GameVersion)(this["PriorityGameVersion"]));
            }
            set {
                this["PriorityGameVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromptForSmogonImport {
            get {
                return ((bool)(this["PromptForSmogonImport"]));
            }
            set {
                this["PromptForSmogonImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetBattleVersion {
            get {
                return ((bool)(this["SetBattleVersion"]));
            }
            set {
                this["SetBattleVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowTrainerOverride {
            get {
                return ((bool)(this["AllowTrainerOverride"]));
            }
            set {
                this["AllowTrainerOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Timeout {
            get {
                return ((int)(this["Timeout"]));
            }
            set {
                this["Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeForms {
            get {
                return ((bool)(this["IncludeForms"]));
            }
            set {
                this["IncludeForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetShiny {
            get {
                return ((bool)(this["SetShiny"]));
            }
            set {
                this["SetShiny"] = value;
            }
        }
    }
}
