//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoModPlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoModPlugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_de {
            get {
                return ResourceManager.GetString("almlang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_en {
            get {
                return ResourceManager.GetString("almlang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_es {
            get {
                return ResourceManager.GetString("almlang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_fr {
            get {
                return ResourceManager.GetString("almlang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_it {
            get {
                return ResourceManager.GetString("almlang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_ja {
            get {
                return ResourceManager.GetString("almlang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_ko {
            get {
                return ResourceManager.GetString("almlang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMSettings=Auto Legality Plugin Settings
        ///
        ///LiveHexUI=LiveHexUI
        ///LiveHexUI.B_ReadCurrent=Read Current Box
        ///LiveHexUI.B_WriteCurrent=Write Current Box
        ///LiveHexUI.checkBox1=Read On Change Box
        ///LiveHexUI.L_IP=IP:
        ///LiveHexUI.L_Port=Port:
        ///LiveHexUI.B_Connect=Connect
        ///LiveHexUI.groupBox1=Boxes
        ///LiveHexUI.checkBox2=Inject In Slot
        ///LiveHexUI.groupBox2=PKM Editor
        ///LiveHexUI.L_ReadOffset=Offset:
        ///LiveHexUI.B_ReadOffset=Read from Offset
        ///LiveHexUI.L_Slot=Slot:
        ///LiveHexUI.L_Box=Box:
        ///LiveHexUI.B_ReadSlot=Read from Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string almlang_zh {
            get {
                return ResourceManager.GetString("almlang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap autolegalitymod {
            get {
                object obj = ResourceManager.GetObject("autolegalitymod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportboxtoshowdown {
            get {
                object obj = ResourceManager.GetObject("exportboxtoshowdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportqrcode {
            get {
                object obj = ResourceManager.GetObject("exportqrcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flagbrew {
            get {
                object obj = ResourceManager.GetObject("flagbrew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap legalizeboxes {
            get {
                object obj = ResourceManager.GetObject("legalizeboxes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap livingdex {
            get {
                object obj = ResourceManager.GetObject("livingdex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuautolegality {
            get {
                object obj = ResourceManager.GetObject("menuautolegality", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mgdbdownload {
            get {
                object obj = ResourceManager.GetObject("mgdbdownload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pglqrcode {
            get {
                object obj = ResourceManager.GetObject("pglqrcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smogongenner {
            get {
                object obj = ResourceManager.GetObject("smogongenner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uploadgpss {
            get {
                object obj = ResourceManager.GetObject("uploadgpss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap urlimport {
            get {
                object obj = ResourceManager.GetObject("urlimport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wifi {
            get {
                object obj = ResourceManager.GetObject("wifi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
